language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install --upgrade pip  # Get a newer version of pip to be able to use many-linux wheels
  - pip install tox

# command to run tests
script: make quality test
